//! 领域C: 动机与价值 (C025-C038)
//! 什么驱动系统采取行动

use crate::core::*;
use super::*;

pub fn domain_c_parameters() -> Vec<ParameterDefinition> {
    vec![
        ParameterDefinition {
            id: ParameterId::parse("C025").unwrap(),
            name: "趋近-回避基线".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "面对中性/陌生刺激时系统的默认行为倾向".into(),
            spectrum: SpectrumType::Bipolar,
            spectrum_labels: ("默认后撤(-1)".into(), "默认前倾(+1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C025a".into(), "C025b".into(), "C025c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("D036").unwrap(), condition: ValueCondition::High, phenomenon: "社交回避+高自主性=独处偏好(非病态)".into() },
                CouplingDescription { parameter: ParameterId::parse("B017").unwrap(), condition: ValueCondition::High, phenomenon: "社交回避+高羞耻=社交恐惧型".into() },
                CouplingDescription { parameter: ParameterId::parse("C030").unwrap(), condition: ValueCondition::Low, phenomenon: "高趋近+低冲动控制=冒险型".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "威胁情境".into(), direction: CollapseDirection::Directional(-1.0), description: "全面回避".into() }],
            drifts: vec![
                DriftPattern { description: "反复成功经验：缓慢偏向+1".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow },
                DriftPattern { description: "反复失败/创伤经验：缓慢偏向-1".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::Slow },
            ],
            reversals: vec![],
            default_value: ParameterValue::bipolar(0.2),
        },
        ParameterDefinition {
            id: ParameterId::parse("C026").unwrap(),
            name: "意义寻求强度".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "系统自动追问「这有什么意义」的频率和深度".into(),
            spectrum: SpectrumType::Unbounded,
            spectrum_labels: ("活着就好(0)".into(), "每件事都追问意义(100/天)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C026a".into(), "C026b".into(), "C026c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::Low, phenomenon: "高意义寻求+低使命感=存在性空虚".into() },
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::High, phenomenon: "高意义寻求+高使命感=找到了答案的追寻者".into() },
                CouplingDescription { parameter: ParameterId::parse("C030").unwrap(), condition: ValueCondition::High, phenomenon: "低意义寻求+高冲动=活在当下的行动派".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "经历重大丧失".into(), direction: CollapseDirection::LowToHigh, description: "「为什么会发生这种事？」".into() }],
            drifts: vec![
                DriftPattern { description: "中年期通常上升(中年危机)".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow },
                DriftPattern { description: "找到稳定信仰/使命后通常下降".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::Slow },
            ],
            reversals: vec![ReversalCondition { trigger: "极度抑郁".into(), from_meaning: "意义寻求".into(), to_meaning: "意义否定(「一切都没有意义」)".into() }],
            default_value: ParameterValue::unbounded(10.0),
        },
        ParameterDefinition {
            id: ParameterId::parse("C027").unwrap(),
            name: "延迟折扣率".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "未来奖赏在当下主观价值中的折扣程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("只要现在(1)".into(), "全押未来(0)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C027a".into(), "C027b".into(), "C027c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C030").unwrap(), condition: ValueCondition::Low, phenomenon: "高折扣+低冲动控制=即时满足型".into() },
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::High, phenomenon: "低折扣+高使命感=为了长远目标牺牲现在".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "压力".into(), direction: CollapseDirection::LowToHigh, description: "急剧偏向1(短视化)".into() }],
            drifts: vec![
                DriftPattern { description: "随年龄通常下降(更愿意等待)".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::VerySlow },
                DriftPattern { description: "贫困环境中通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow },
            ],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("C028").unwrap(),
            name: "自主性需求".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "被指令/控制时系统产生的阻抗力强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("被指令=舒适(0)".into(), "被指令=本能反抗(100)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C028a".into(), "C028b".into(), "C028c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C031").unwrap(), condition: ValueCondition::High, phenomenon: "高自主+高支配=我要主导但不要被主导".into() },
                CouplingDescription { parameter: ParameterId::parse("D037").unwrap(), condition: ValueCondition::Low, phenomenon: "高自主+低规则遵循=反规范倾向".into() },
                CouplingDescription { parameter: ParameterId::parse("C031").unwrap(), condition: ValueCondition::Low, phenomenon: "低自主+低支配=顺从型".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "被过度控制".into(), direction: CollapseDirection::LowToHigh, description: "逆反爆发".into() }],
            drifts: vec![DriftPattern { description: "青春期通常上升；成年后稳定".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("C029").unwrap(),
            name: "胜任感锚点".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "系统认为自己「够好」所需的最低客观证据数量".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("永远不够好(∞)".into(), "做了一点就够了(0)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C029a".into(), "C029b".into(), "C029c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E045").unwrap(), condition: ValueCondition::High, phenomenon: "永远不够好但对外声称很好(自恋-脆弱型)".into() },
                CouplingDescription { parameter: ParameterId::parse("E044").unwrap(), condition: ValueCondition::High, phenomenon: "永远不够好+反复咀嚼失败=完美主义型反刍".into() },
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::High, phenomenon: "做了一点就觉得够了+精心展示=自我推销型".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "重大失败".into(), direction: CollapseDirection::LowToHigh, description: "胜任感崩塌".into() }],
            drifts: vec![DriftPattern { description: "随成功经验积累通常下降(更容易觉得自己够好)".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("C030").unwrap(),
            name: "冲动控制缓冲".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "冲动产生到行为执行之间的缓冲时间长度".into(),
            spectrum: SpectrumType::Unbounded,
            spectrum_labels: ("冲动=行动(0s)".into(), "冲动…(缓冲)…行动(∞s)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C030a".into(), "C030b".into(), "C030c".into(), "C030d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C027").unwrap(), condition: ValueCondition::High, phenomenon: "低缓冲+高折扣=即时满足冲动型".into() },
                CouplingDescription { parameter: ParameterId::parse("A008").unwrap(), condition: ValueCondition::High, phenomenon: "低缓冲+高威胁放大=先发制人型暴力".into() },
                CouplingDescription { parameter: ParameterId::parse("B019").unwrap(), condition: ValueCondition::High, phenomenon: "高缓冲+高攻击转化=预谋型暴力(延迟但必然)".into() },
            ],
            collapses: vec![
                CollapseCondition { trigger: "酒精/物质影响".into(), direction: CollapseDirection::HighToLow, description: "C030急剧下降".into() },
                CollapseCondition { trigger: "极度疲劳".into(), direction: CollapseDirection::HighToLow, description: "C030急剧下降".into() },
            ],
            drifts: vec![
                DriftPattern { description: "随年龄通常上升(更好的冲动控制)".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow },
                DriftPattern { description: "可通过训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate },
            ],
            reversals: vec![],
            default_value: ParameterValue::unbounded(5.0),
        },
        ParameterDefinition {
            id: ParameterId::parse("C031").unwrap(),
            name: "支配-顺从倾向".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "在人际等级中系统默认追求的位置".into(),
            spectrum: SpectrumType::Bipolar,
            spectrum_labels: ("自愿服从(-1)".into(), "必须主导(+1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C031a".into(), "C031b".into(), "C031c".into(), "C031d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E045").unwrap(), condition: ValueCondition::Low, phenomenon: "高支配+低内隐自尊=用控制他人逃避自我厌恶".into() },
            ],
            collapses: vec![
                CollapseCondition { trigger: "获得权力".into(), direction: CollapseDirection::Directional(1.0), description: "C031a可能从-1跳变到+1(权力改变行为)".into() },
                CollapseCondition { trigger: "失去权力".into(), direction: CollapseDirection::Directional(-1.0), description: "C031b可能从+1跳变到-1(被迫顺从)".into() },
            ],
            drifts: vec![DriftPattern { description: "社会地位上升时C031a通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::bipolar(0.0),
        },
        ParameterDefinition {
            id: ParameterId::parse("C032").unwrap(),
            name: "权力动机".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "渴望影响/控制他人或环境的驱力强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("影响他人=无感(0)".into(), "控制他人=核心驱力(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C032a".into(), "C032b".into(), "C032c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::High, phenomenon: "高权力+高使命感=「我追求权力是为了更伟大的善」".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "高权力+低内疚=不择手段型".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "高权力+高内疚=边掌权边自我怀疑".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "获得权力".into(), direction: CollapseDirection::Variable, description: "可能下降(满足)或上升(欲壑难填)".into() }],
            drifts: vec![],
            reversals: vec![ReversalCondition { trigger: "权力导致重大负面后果".into(), from_meaning: "权力动机".into(), to_meaning: "权力厌恶".into() }],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("C033").unwrap(),
            name: "亲和动机".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "建立和维持温暖人际关系的驱力强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("人际=工具(0)".into(), "人际=目的(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C033a".into(), "C033b".into(), "C033c".into(), "C033d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C031").unwrap(), condition: ValueCondition::High, phenomenon: "高亲和+高支配=「我爱你所以你要听我的」".into() },
                CouplingDescription { parameter: ParameterId::parse("D038").unwrap(), condition: ValueCondition::High, phenomenon: "高亲和+高欺骗舒适=用温暖获取信任后利用".into() },
                CouplingDescription { parameter: ParameterId::parse("C032").unwrap(), condition: ValueCondition::High, phenomenon: "低亲和+高权力=冷酷的权力追求者".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "被亲近者严重背叛".into(), direction: CollapseDirection::HighToLow, description: "C033可能从高跳变到零".into() }],
            drifts: vec![DriftPattern { description: "长期孤独后C033可能下降(适应)或上升(渴望)".into(), direction: DriftDirection::Variable, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.6),
        },
        ParameterDefinition {
            id: ParameterId::parse("C034").unwrap(),
            name: "地位渴求".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "需要感到自己比他人优越/受他人尊重的心理驱力强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("地位=无所谓(0)".into(), "地位=生命意义(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C034a".into(), "C034b".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B023d").unwrap(), condition: ValueCondition::High, phenomenon: "高地位渴求+反向嫉妒=高位者嫉妒低位者的自由".into() },
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::High, phenomenon: "高地位渴求+高印象管理=精心维护公共形象".into() },
                CouplingDescription { parameter: ParameterId::parse("E045").unwrap(), condition: ValueCondition::Low, phenomenon: "高地位渴求+低内隐自尊=需要外部崇拜维持自我".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "获得顶级地位".into(), direction: CollapseDirection::Variable, description: "可能下降(满足)或上升(害怕失去)".into() }],
            drifts: vec![DriftPattern { description: "随年龄通常先升后降(中年顶峰后下降)".into(), direction: DriftDirection::Variable, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("C035").unwrap(),
            name: "利他惩罚倾向".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "愿意自掏成本惩罚不公平/违规行为的强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("不公=无视(0)".into(), "不公=自掏成本也要罚(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C035a".into(), "C035b".into(), "C035c".into(), "C035d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B022").unwrap(), condition: ValueCondition::High, phenomenon: "高惩罚+高怨恨=「惩罚不公」可能是「发泄私怨」".into() },
                CouplingDescription { parameter: ParameterId::parse("C026").unwrap(), condition: ValueCondition::High, phenomenon: "高惩罚+高意义寻求=将惩罚不公视为人生意义".into() },
                CouplingDescription { parameter: ParameterId::parse("E042").unwrap(), condition: ValueCondition::High, phenomenon: "高惩罚+高道德耦合=道德化惩罚(「神圣的审判」)".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "惩罚后看到被惩罚者的痛苦".into(), direction: CollapseDirection::HighToLow, description: "「我是不是太过分了」".into() }],
            drifts: vec![],
            reversals: vec![ReversalCondition { trigger: "自身成为被惩罚对象".into(), from_meaning: "惩罚倾向".into(), to_meaning: "对惩罚的恐惧".into() }],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("C036").unwrap(),
            name: "欺骗接受度".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "系统将欺骗视为合理行为手段的程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("谎言=不可接受(0)".into(), "谎言=合理工具(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C036a".into(), "C036b".into(), "C036c".into(), "C036d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::High, phenomenon: "高自我欺骗+高印象管理=自己都信了自己的假面具".into() },
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::High, phenomenon: "高欺骗接受+高使命感=「为了更伟大的善可以说谎」".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "高欺骗+高内疚=边说谎边自我厌恶".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "被自己人用同样的方式欺骗".into(), direction: CollapseDirection::HighToLow, description: "「原来被骗这么痛」".into() }],
            drifts: vec![DriftPattern { description: "在需要频繁策略性沟通的环境中通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("C037").unwrap(),
            name: "价值-行为一致性".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "系统声称的价值观与实际行为之间的相关程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("说的≠做的(0)".into(), "言行完全一致(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C037a".into(), "C037b".into(), "C037c".into(), "C037d".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C036c").unwrap(), condition: ValueCondition::High, phenomenon: "言行不一+高自我欺骗=不知道自己在不一致".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "被公开揭穿言行不一".into(), direction: CollapseDirection::Variable, description: "C037a可能跳变".into() }],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.6),
        },
        ParameterDefinition {
            id: ParameterId::parse("C038").unwrap(),
            name: "刺激寻求".into(),
            domain: ParameterDomain::MotivationValue,
            definition: "为获得快感/兴奋而追求新奇/危险/禁忌体验的驱力强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("平静=理想(0)".into(), "刺激=必需(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["C038a".into(), "C038b".into(), "C038c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C030").unwrap(), condition: ValueCondition::Low, phenomenon: "高刺激寻求+低冲动控制=高风险行为型".into() },
                CouplingDescription { parameter: ParameterId::parse("D037").unwrap(), condition: ValueCondition::Low, phenomenon: "高刺激寻求+低规则遵循=反规范冒险型".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "经历重大负面后果".into(), direction: CollapseDirection::HighToLow, description: "C038可能从高跳变到低".into() }],
            drifts: vec![
                DriftPattern { description: "青春期通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow },
                DriftPattern { description: "成年后缓慢下降".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::Slow },
            ],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
    ]
}
