//! 领域H: 身体-环境耦合 (H067-H084)
//! 身体与环境如何交互影响心理参数

use crate::core::*;
use super::*;

pub fn domain_h_parameters() -> Vec<ParameterDefinition> {
    vec![
        ParameterDefinition {
            id: ParameterId::parse("H067").unwrap(),
            name: "坐姿-思维关联".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "身体姿态对思维模式的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("姿态=无关(0)".into(), "姿态=决定思维(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("H068").unwrap(),
            name: "呼吸-情绪耦联".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "呼吸模式与情绪状态的互锁强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("呼吸独立于情绪(0)".into(), "呼吸=情绪开关(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![CouplingDescription {
                parameter: ParameterId::parse("A003").unwrap(), condition: ValueCondition::High,
                phenomenon: "高内感受+高呼吸耦联=通过呼吸精准调控情绪".into(),
            }],
            collapses: vec![],
            drifts: vec![DriftPattern { description: "可通过呼吸训练增强".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H069").unwrap(),
            name: "手势-语速锁定".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "手势与言语节奏的同步程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("说话时手不动(0)".into(), "手势与语速完全同步(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.6),
        },
        ParameterDefinition {
            id: ParameterId::parse("H070").unwrap(),
            name: "温度-社交距离".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "环境温度对社交距离偏好的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("温度无关(0)".into(), "冷=靠近/热=远离(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("H071").unwrap(),
            name: "饱腹-慷慨".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "饥饿/饱腹状态对慷慨行为的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("饱饿无关(0)".into(), "饱=慷慨/饿=自私(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("H072").unwrap(),
            name: "昼夜节律-创造力".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "昼夜节律阶段对创造性思维的影响幅度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("全天一样(0)".into(), "晨/夜型差异极大(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![DriftPattern { description: "随年龄：青少年偏向夜型，老年偏向晨型".into(), direction: DriftDirection::Variable, rate_category: DriftRate::VerySlow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H073").unwrap(),
            name: "微表情抑制力".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "抑制面部微表情泄露真实情绪的能力".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("情绪=写在脸上(0)".into(), "脸=完美面具(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![CouplingDescription {
                parameter: ParameterId::parse("F059").unwrap(), condition: ValueCondition::High,
                phenomenon: "高抑制+高欺骗舒适=完美说谎者".into(),
            }],
            collapses: vec![],
            drifts: vec![DriftPattern { description: "可通过训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H074").unwrap(),
            name: "疼痛-攻击链接".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "身体疼痛转化为攻击冲动的强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("疼痛=忍耐(0)".into(), "疼痛=攻击(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![CouplingDescription {
                parameter: ParameterId::parse("B019").unwrap(), condition: ValueCondition::High,
                phenomenon: "高疼痛-攻击链接+高愤怒转化=疼痛触发攻击链".into(),
            }],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("H075").unwrap(),
            name: "光照-决策速度".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "环境光照强度对决策速度的影响".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("光照无关(0)".into(), "亮=快决策/暗=慢决策(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("H076").unwrap(),
            name: "运动-情绪提升".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "身体运动对情绪状态的提升幅度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("运动=无效(0)".into(), "运动=强力抗抑郁(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.6),
        },
        ParameterDefinition {
            id: ParameterId::parse("H077").unwrap(),
            name: "睡眠债务-认知衰减".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "睡眠不足对认知功能的衰减速率".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("熬夜=无影响(0)".into(), "少睡1h=认知崩溃(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H078").unwrap(),
            name: "噪音-压力耦联".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "环境噪音对压力水平的提升幅度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("噪音=无所谓(0)".into(), "噪音=压力源(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("H079").unwrap(),
            name: "气味-记忆唤起率".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "气味触发自传体记忆的概率和强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("气味=无记忆(0)".into(), "每种气味=一段往事(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H080").unwrap(),
            name: "触觉-信任关联".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "身体接触对信任建立的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("触碰=无关(0)".into(), "触碰=信任开关(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("H081").unwrap(),
            name: "饥饿-风险偏好".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "饥饿状态对风险决策的影响方向与强度".into(),
            spectrum: SpectrumType::Bipolar,
            spectrum_labels: ("饿=保守(-1)".into(), "饿=冒险(+1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::bipolar(0.2),
        },
        ParameterDefinition {
            id: ParameterId::parse("H082").unwrap(),
            name: "姿势-权力感映射".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "身体姿势(扩张/收缩)对权力感的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("姿势=无关(0)".into(), "扩张姿势=权力感(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("H083").unwrap(),
            name: "温度-攻击性".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "环境温度对攻击行为的影响强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("温度=无关(0)".into(), "热=暴躁(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("H084").unwrap(),
            name: "海拔-思维抽象度".into(),
            domain: ParameterDomain::BodyEnvironmentCoupling,
            definition: "物理高度对思维抽象程度的影响".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("高度=无关(0)".into(), "高处=抽象思维(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.2),
        },
    ]
}
