//! 领域E: 元认知与自我 (E043-E055)
//! 系统如何观察和定义自己

use crate::core::*;
use super::*;

pub fn domain_e_parameters() -> Vec<ParameterDefinition> {
    vec![
        ParameterDefinition {
            id: ParameterId::parse("E043").unwrap(),
            name: "思维标签化频率".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统能够将自身思维过程作为观察对象的频率".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("思维=透明(0)".into(), "「我注意到我在焦虑地思考」(高频率)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B014").unwrap(), condition: ValueCondition::High, phenomenon: "高元认知+高策略库=情绪调节大师".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "高元认知+高内疚=「我知道我在内疚，但我停不下来」".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "压力".into(), direction: CollapseDirection::HighToLow, description: "急剧下降".into() }],
            drifts: vec![DriftPattern { description: "可通过正念训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![ReversalCondition { trigger: "过度自我监控".into(), from_meaning: "元认知".into(), to_meaning: "行为瘫痪".into() }],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("E044").unwrap(),
            name: "反刍思维强度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统反复咀嚼负面经历的自动化程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("负面经历=翻篇(0)".into(), "负面经历=无限循环(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E044a".into(), "E044b".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B022").unwrap(), condition: ValueCondition::High, phenomenon: "反复咀嚼+怨恨不散=怨恨-反刍循环".into() },
                CouplingDescription { parameter: ParameterId::parse("B013a").unwrap(), condition: ValueCondition::High, phenomenon: "反复咀嚼+高情绪附着力=每次反刍都重新受伤".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "压力".into(), direction: CollapseDirection::LowToHigh, description: "急剧上升".into() }],
            drifts: vec![DriftPattern { description: "可通过CBT/正念训练降低".into(), direction: DriftDirection::Decreasing, rate_category: DriftRate::Moderate }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("E045").unwrap(),
            name: "内隐自尊".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统在潜意识层面对自己的积极/消极评价".into(),
            spectrum: SpectrumType::Bipolar,
            spectrum_labels: ("潜意识自我=负面(-1)".into(), "潜意识自我=正面(+1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::High, phenomenon: "低内隐+高外显=表面自信内心自卑(脆弱型)".into() },
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::Low, phenomenon: "高内隐+低外显=内心自信但不张扬(沉稳型)".into() },
                CouplingDescription { parameter: ParameterId::parse("C031").unwrap(), condition: ValueCondition::High, phenomenon: "低内隐+高支配=用控制他人逃避自我厌恶".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "重大失败".into(), direction: CollapseDirection::HighToLow, description: "E045可能急剧下降".into() }],
            drifts: vec![DriftPattern { description: "可通过长期心理治疗缓慢改变".into(), direction: DriftDirection::Variable, rate_category: DriftRate::VerySlow }],
            reversals: vec![],
            default_value: ParameterValue::bipolar(0.2),
        },
        ParameterDefinition {
            id: ParameterId::parse("E046").unwrap(),
            name: "外显自尊".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统在意识层面声称的自我价值感".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("声称的自我价值=低(0)".into(), "声称的自我价值=高(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E046a".into(), "E046b".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E045").unwrap(), condition: ValueCondition::Low, phenomenon: "高外显+低内隐=脆弱型自恋".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "公开羞辱".into(), direction: CollapseDirection::HighToLow, description: "E046a可能急剧下降".into() }],
            drifts: vec![DriftPattern { description: "随成功经验积累通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("E047").unwrap(),
            name: "自我感知校准度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统对自身能力/性格/道德的评价与客观测量的偏差程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("自我评价=严重偏差(0%)".into(), "自我评价=客观精准(100%)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E047a".into(), "E047b".into(), "E047c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E045").unwrap(), condition: ValueCondition::Low, phenomenon: "夸大能力+低内隐自尊=补偿型自夸".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "夸大道德+低内疚=自认圣人型".into() },
                CouplingDescription { parameter: ParameterId::parse("E044").unwrap(), condition: ValueCondition::High, phenomenon: "贬低自己+反复咀嚼=抑郁型自我认知".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "获得客观反馈".into(), direction: CollapseDirection::Variable, description: "E047可能跳变".into() }],
            drifts: vec![DriftPattern { description: "可通过360度反馈训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("E048").unwrap(),
            name: "道德推脱能力".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统为自身不道德行为找到合理化理由的容易程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("错=错(0)".into(), "错=可合理化(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E048a".into(), "E048b".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "高推脱+低内疚=完美的自我合理化".into() },
                CouplingDescription { parameter: ParameterId::parse("E040").unwrap(), condition: ValueCondition::High, phenomenon: "高推脱+高使命=「为了使命可以不择手段」".into() },
                CouplingDescription { parameter: ParameterId::parse("C036c").unwrap(), condition: ValueCondition::High, phenomenon: "高推脱+高自我欺骗=自己都信了合理化".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "合理化被外部证据粉碎".into(), direction: CollapseDirection::Variable, description: "E048可能跳变".into() }],
            drifts: vec![DriftPattern { description: "在需要频繁道德妥协的环境中通常上升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("E049").unwrap(),
            name: "责任归因偏向".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统将事件原因归因于自身(-1)还是外部(+1)的默认偏向".into(),
            spectrum: SpectrumType::Bipolar,
            spectrum_labels: ("问题=我(-1)".into(), "问题=世界(+1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E049a".into(), "E049b".into(), "E049c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "罪行=环境逼的+不内疚=完全外化型".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "罪行=我的错+高内疚=自我折磨型".into() },
            ],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::bipolar(0.0),
        },
        ParameterDefinition {
            id: ParameterId::parse("E050").unwrap(),
            name: "自我批评强度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统对自身错误/缺陷产生自我批评的强度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("错误=无视(0)".into(), "错误=自我鞭笞(1)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E050a".into(), "E050b".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "高自我批评+高内疚=自我惩罚型".into() },
                CouplingDescription { parameter: ParameterId::parse("E048").unwrap(), condition: ValueCondition::High, phenomenon: "低自我批评+高推脱=从不反思型".into() },
                CouplingDescription { parameter: ParameterId::parse("A009").unwrap(), condition: ValueCondition::Low, phenomenon: "对自己苛刻+对他人冷漠=自我-他人撕裂".into() },
            ],
            collapses: vec![],
            drifts: vec![DriftPattern { description: "可通过心理治疗调节".into(), direction: DriftDirection::Variable, rate_category: DriftRate::Slow }],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("E051").unwrap(),
            name: "使命感清晰度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统对「我为何而活」有明确答案的程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("为何而活=？(0)".into(), "为何而活=！(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C026").unwrap(), condition: ValueCondition::Low, phenomenon: "高使命+低意义寻求=找到了答案不再追问".into() },
                CouplingDescription { parameter: ParameterId::parse("C032").unwrap(), condition: ValueCondition::High, phenomenon: "高使命+高权力=「权力是完成使命的工具」".into() },
                CouplingDescription { parameter: ParameterId::parse("D040").unwrap(), condition: ValueCondition::High, phenomenon: "高使命+高攻击=为使命而战".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "高使命+低内疚=为使命不择手段".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "使命失败/幻灭".into(), direction: CollapseDirection::HighToLow, description: "E051可能从极高跳变到零".into() }],
            drifts: vec![DriftPattern { description: "青年期通常上升；中年后可能稳定或转变".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Slow }],
            reversals: vec![ReversalCondition { trigger: "使命幻灭".into(), from_meaning: "使命感".into(), to_meaning: "虚无感".into() }],
            default_value: ParameterValue::normalized(0.3),
        },
        ParameterDefinition {
            id: ParameterId::parse("E052").unwrap(),
            name: "道德-审美耦合度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统感知「善」与感知「美」在大脑中的重叠程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("善≠美(0)".into(), "善=美(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C035").unwrap(), condition: ValueCondition::High, phenomenon: "高道德耦合+高利他惩罚=惩罚恶人是审美体验".into() },
                CouplingDescription { parameter: ParameterId::parse("C026").unwrap(), condition: ValueCondition::High, phenomenon: "高道德耦合+高意义寻求=在道德中寻找美/意义".into() },
            ],
            collapses: vec![],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.4),
        },
        ParameterDefinition {
            id: ParameterId::parse("E053").unwrap(),
            name: "矛盾共存耐受".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统同时持有冲突信念/情感而不产生焦虑的能力".into(),
            spectrum: SpectrumType::Unbounded,
            spectrum_labels: ("冲突=必须解决(0)".into(), "冲突=可以共存(∞分钟)".into()),
            granularity: ParameterGranularity::Decomposable(vec!["E053a".into(), "E053b".into(), "E053c".into()]),
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C037").unwrap(), condition: ValueCondition::Low, phenomenon: "低矛盾耐受+言行不一=认知失调痛苦".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "压力".into(), direction: CollapseDirection::HighToLow, description: "E053急剧下降".into() }],
            drifts: vec![DriftPattern { description: "可通过辩证思维训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![],
            default_value: ParameterValue::unbounded(10.0),
        },
        ParameterDefinition {
            id: ParameterId::parse("E054").unwrap(),
            name: "框架重构力".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统将事件从一种意义框架重新定义为另一种意义框架的能力".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("失败=失败(0)".into(), "失败=数据(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("E048").unwrap(), condition: ValueCondition::High, phenomenon: "高重构+高推脱=任何恶行都能被重新定义为善行".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::High, phenomenon: "高重构+高内疚=试图重构但内疚阻止(重构失败)".into() },
            ],
            collapses: vec![],
            drifts: vec![DriftPattern { description: "可通过认知训练提升".into(), direction: DriftDirection::Increasing, rate_category: DriftRate::Moderate }],
            reversals: vec![ReversalCondition { trigger: "极端情况".into(), from_meaning: "重构力".into(), to_meaning: "现实否认".into() }],
            default_value: ParameterValue::normalized(0.5),
        },
        ParameterDefinition {
            id: ParameterId::parse("E055").unwrap(),
            name: "自我欺骗强度".into(),
            domain: ParameterDomain::MetacognitionSelf,
            definition: "系统相信自己明知为假的自我叙述的程度".into(),
            spectrum: SpectrumType::Normalized,
            spectrum_labels: ("对自己诚实(0)".into(), "完全相信自己编织的谎言(1)".into()),
            granularity: ParameterGranularity::Atomic,
            couplings: vec![
                CouplingDescription { parameter: ParameterId::parse("C036c").unwrap(), condition: ValueCondition::High, phenomenon: "高自我欺骗+高自我欺骗接受=完美的自我谎言".into() },
                CouplingDescription { parameter: ParameterId::parse("E046").unwrap(), condition: ValueCondition::High, phenomenon: "高自我欺骗+高外显自尊=真诚地相信自己是伟大的人".into() },
                CouplingDescription { parameter: ParameterId::parse("B015").unwrap(), condition: ValueCondition::Low, phenomenon: "高自我欺骗+低内疚=真诚地相信自己没有伤害任何人".into() },
            ],
            collapses: vec![CollapseCondition { trigger: "自我欺骗被外部证据粉碎".into(), direction: CollapseDirection::HighToLow, description: "可能跳变".into() }],
            drifts: vec![],
            reversals: vec![],
            default_value: ParameterValue::normalized(0.3),
        },
    ]
}
